name: dpkg-package
on: [push, pull_request]
jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-bionic, ubuntu-focal, ubuntu-groovy, debian-testing]
        fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: bverhagen/exec-helper:${{ matrix.os }}
    steps:
      - name: Install git PPA   # Workaround for installing git 2.18+ on Ubuntu Bionic
        if: matrix.os == 'ubuntu-bionic'
        run: |
            apt-get update
            apt-get install --yes software-properties-common
            add-apt-repository ppa:git-core/ppa
      - name: Install dependencies
        run: |
            export DEBIAN_FRONTEND=noninteractive
            echo 'tzdata tzdata/Areas select Europe' > debconf
            echo 'tzdata tzdata/Zones/Europe select Brussels' >> debconf
            debconf-set-selections debconf
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install --yes build-essential lsb-release python3 python3-pip git debhelper-compat lintian
      - name: Install gitchangelog
        run: |
            apt-get --yes install python3 python3-mako curl
            curl -sSL https://raw.githubusercontent.com/vaab/gitchangelog/master/src/gitchangelog/gitchangelog.py > /usr/local/bin/gitchangelog
            chmod +x /usr/local/bin/gitchangelog
            [ -f /usr/bin/python ] || ln -s python3 /usr/bin/python
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0      # Whole history is required to determine the version of the package
            submodules: true
      - name: Build source files
        run: exec-helper package-src --package-tech dpkg
      - name: Check src package
        run: lintian --allow-root --no-cfg dist/source/*.dsc dist/source/*.changes
      - name: Build binary package
        run: exec-helper package-bin --package-tech dpkg
      - name: Check binary package
        run: lintian --allow-root --no-cfg dist/binary/*.dsc dist/binary/*.changes
      - name: Upload source package
        uses: actions/upload-artifact@v2
        with:
          name: dpkg-src-package_${{ matrix.os }}
          path: dist/source/
          retention-days: 5
      - name: Upload binary package
        uses: actions/upload-artifact@v2
        with:
          name: dpkg-binary-package_${{ matrix.os }}
          path: dist/binary/
          retention-days: 5
